#!/bin/sh

rm -fr \
    aclocal.m4 \
    autom4te.cache \
    $(find . -name "Makefile.in") \
    config/{compile,config.guess,config.sub,depcomp,install-sh,missing,ylwrap} \
    configure

autoreconf --verbose --install --force

ls -lrtha config

#fix ylwrap
patch -p1 config/ylwrap < config/patch_ylwrap
